[build]
    publish = "build/"
    command = "pnpm build"

[context.branch-deploy]
    command = "pnpm noIndex"

[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = false
    minify = false
[build.processing.js]
    bundle = false
    minify = false
[build.processing.html]
    pretty_urls = false
[build.processing.images]
    compress = true